### ISSUE TITLE
When only one answer possible, do not inform about possibility on other items 

### ISSUE THREAD

**Issue by ClementMayer** [LabeliaLabs/referentiel-evaluation-dsrc#178]
Exemple : 
Question 2.5 
Nous ne traitons pas de thématique ou ne portons pas de projet correspondant à des cas de figure avec des risques de discrimination à l'encontre de certains groupes sociaux (genre, origine, âge, etc.) | (Lorsque cette réponse est sélectionnée, les autres ne peuvent pas l'être)

--> une seule réponse possible donc pas besoin de préciser que les autres ne sont pas selectionnables.

**Comment by bowni** [comment]
A priori ça n'est pas un attribut du référentiel, je pense que ça se situe au niveau du rendu front dans la plateforme d'assessment

**Comment by bowni** [comment]
Déplacée vers le repo plateforme d'assessment - je classe l'issue ici
